### ISSUE TITLE
Clicking links of online pdfs results in an error

### ISSUE THREAD

**Issue by keyansheng** [Emano-Waldeck/pdf-reader#2]
When I left click, middle click or ctrl+click a pdf link, it shows this error:
<img src="https://user-images.githubusercontent.com/65121402/85941696-e34cab00-b956-11ea-8157-503e3f88d08d.png" alt="Error message: ieepebpjnkhaiioojkepfniodjmjjihl is blocked. Requests to the server have been blocked by an extension. Try disabling your extensions. ERR_BLOCKED_BY_CLIENT" width="300">
It works if I access the link directly (pasting the link in the url bar and pressing enter) or if I right click and choose to open it in a new tab.

For google drive pdf links `https://drive.google.com/file/d/file_id_goes_here/view`, clicking the download button results in the same error. Right clicking is disabled so the workaround doesn't work. The only way to download the pdf is to click download, click the url bar and press enter quickly enough such that the extension hasn't loaded yet.

**Comment by Emano-Waldeck** [comment]
Thanks for the report. Should be fixed by 0.1.6 release.

**Comment by ParticleMon** [comment]
When might 0.1.6 be released? This issue has not resolved itself through the intervening years of Chromium updates.

**Comment by Emano-Waldeck** [comment]
@ParticleMon this issue has already been fixed. The current version of the extension is 0.4.7. 

I am not able to reproduce this on Chromium.

**Comment by ParticleMon** [comment]
This site still has up to only 0.1.5, making it seem current. At the time of writing, I had 0.4.6, which exhibits the issue, which 0.4.7 fixes (perhaps unintentionally).
